pipeline{
    agent any
    stages{
        stage('git pull'){
            steps{
                checkout scm
                echo "project pulled from git"
            }
        }
        stage('docker build'){
            steps{
                sh 'docker build -t container ./backend'
            }
            
        }
    }
}