pipeline {
    agent any
    stages {
        stage('git pull') {
            steps {
                checkout scm
                echo 'project pulled from git'
            }
        }
        stage('docker build') {
            steps {
                script {
                    def dockerImg = docker.build('./backend')
                    def dockerRun = dockerImg.run('-p 5000:80 --name c1')
                }
            }
        }
    }
}
